
# === CPR-TaG-Net 训练配置文件 ===

model:
  name: CPRTaGNet
  image_condition_channels: 1
  node_feature_dim: 54
  tps_sample_num: 64
  tfg_radius: 10.0

training:
  epochs: 100
  batch_size: 4
  lr: 0.0005
  weight_decay: 1e-5
  alpha: 0.5  # label loss vs segmentation loss

dataset:
  train_data_path: ./data/train_data.pkl
  val_data_path: ./data/val_data.pkl
  num_workers: 4

loss:
  label: CrossEntropy
  seg: BCEWithLogits

log:
  save_dir: ./checkpoints/
  log_dir: ./logs/
  save_interval: 10
